version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: inventor-container
    environment:
      MYSQL_ROOT_PASSWORD: mysqlTest
      MYSQL_DATABASE: inventor-management-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: upperclasswoman
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always