version: '3.8'

services:
  inventory-management:
    image: postgres:latest
    container_name: inventory_management
    environment:
      POSTGRES_USER: koko
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: inventory_management
    ports:
      - "5432:5432"
    volumes:
      - inventory_data:/var/lib/postgresql/data

volumes:
  inventory_data:

networks:
  inventory:
    driver: bridge
