spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_management
    username: koko
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081

flickr:
  apiKey: 95362056e8ece9e2f8899e9d5f88192e
  apiSecret: 7689372e2653c903
  appKey: 72157720847629347-c584f0411627be1b
  appSecret: 8e2081bcba21c5db