######################## PostgreSQL Database Config #############################
spring:
  datasource:
    url: ${INVENTORY.DATABASE.POSTGRESQL}
    username: ${INVENTORY.DATABASE.USERNAME}
    password: ${INVENTORY.DATABASE.PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: inventory
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  ########################## Flyway Database Config ###############################
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 1.0.0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    locations: classpath:db/migration/structure, classpath:db/migration/prodData
    validate-on-migrate: true
    default-schema: inventory

  ########################## Security Config with Keycloak ########################

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}

app:
  keycloak:
    realm: ${INVENTORY.KEYCLOAK.REALM}
    serverUrl: ${INVENTORY.KEYCLOAK.SERVER_URL}
  admin:
    clientId: ${INVENTORY.KEYCLOAK.CLIENT_ID}
    clientSecret: ${INVENTORY.KEYCLOAK.CLIENT_SECRET}

server:
  port: 8081


flickr:
  apiKey: 95362056e8ece9e2f8899e9d5f88192e
  apiSecret: 7689372e2653c903
  appKey: 72157720847629347-c584f0411627be1b
  appSecret: 8e2081bcba21c5db