CREATE TABLE articles
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_date      TIMESTAMP WITHOUT TIME ZONE,
    code_articles           VARCHAR(255),
    designation             VARCHAR(255),
    prix_unitaire_hors_taxe DECIMAL,
    taux_tva                DECIMAL,
    prix_unitairettc        DECIMAL,
    photo                   VARCHAR(255),
    id_categories           BIGINT,
    id_enterprise           BIGINT,
    CONSTRAINT pk_articles PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    code_categorie     VARCHAR(255),
    designation        VARCHAR(255),
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE clients
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    nom                VARCHAR(255),
    prenom             VARCHAR(255),
    photo              VARCHAR(255),
    email              VARCHAR(255),
    num_tel            VARCHAR(255),
    id_enterprise      BIGINT,
    adresse_1          VARCHAR(255),
    adresse_2          VARCHAR(255),
    ville              VARCHAR(255),
    code_postal        VARCHAR(255),
    pays               VARCHAR(255),
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

CREATE TABLE commande_clients
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_date   TIMESTAMP WITHOUT TIME ZONE,
    code_commande_client VARCHAR(255),
    date_commande        TIMESTAMP WITHOUT TIME ZONE,
    etat_commande        VARCHAR(255),
    id_client            BIGINT,
    CONSTRAINT pk_commandeclients PRIMARY KEY (id)
);

CREATE TABLE commande_fournisseurs
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_date        TIMESTAMP WITHOUT TIME ZONE,
    code_commande_fournisseur VARCHAR(255),
    date_commande             TIMESTAMP WITHOUT TIME ZONE,
    etat_commande             VARCHAR(255),
    id_fournisseur            BIGINT,
    CONSTRAINT pk_commandefournisseurs PRIMARY KEY (id)
);

CREATE TABLE entreprises
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    nom_enterprise     VARCHAR(255),
    description        VARCHAR(255),
    code_fiscal        VARCHAR(255),
    photo              VARCHAR(255),
    email              VARCHAR(255),
    num_tel            VARCHAR(255),
    site_web           VARCHAR(255),
    adresse_1          VARCHAR(255),
    adresse_2          VARCHAR(255),
    ville              VARCHAR(255),
    code_postal        VARCHAR(255),
    pays               VARCHAR(255),
    CONSTRAINT pk_entreprises PRIMARY KEY (id)
);

CREATE TABLE fournisseurs
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    nom                VARCHAR(255),
    prenom             VARCHAR(255),
    photo              VARCHAR(255),
    email              VARCHAR(255),
    num_tel            VARCHAR(255),
    id_enterprise      BIGINT,
    adresse_1          VARCHAR(255),
    adresse_2          VARCHAR(255),
    ville              VARCHAR(255),
    code_postal        VARCHAR(255),
    pays               VARCHAR(255),
    CONSTRAINT pk_fournisseurs PRIMARY KEY (id)
);

CREATE TABLE ligne_commande_clients
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    quantite           DECIMAL,
    prix_unitaire      DECIMAL,
    id_article         BIGINT,
    id_commande_client BIGINT,
    CONSTRAINT pk_lignecommandeclients PRIMARY KEY (id)
);

CREATE TABLE ligne_commande_fournisseurs
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_date      TIMESTAMP WITHOUT TIME ZONE,
    quantite                DECIMAL,
    prix_unitaire           DECIMAL,
    id_commande_fournisseur BIGINT,
    id_article              BIGINT,
    CONSTRAINT pk_lignecommandefournisseurs PRIMARY KEY (id)
);

CREATE TABLE ligne_ventes
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    quantite           DECIMAL,
    prix_unitaire      DECIMAL,
    id_vente           BIGINT,
    id_articles        BIGINT,
    CONSTRAINT pk_ligneventes PRIMARY KEY (id)
);

CREATE TABLE mouvement_stock
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    date_mouvement     TIMESTAMP WITHOUT TIME ZONE,
    quantite           DECIMAL,
    type_move_stock    VARCHAR(255),
    source_move_stock  VARCHAR(255),
    id_article         BIGINT,
    CONSTRAINT pk_mouvementstock PRIMARY KEY (id)
);

CREATE TABLE ventes
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    code_vente         VARCHAR(255),
    id_enterprise      BIGINT,
    date_vente         TIMESTAMP WITHOUT TIME ZONE,
    commentaires       VARCHAR(255),
    CONSTRAINT pk_ventes PRIMARY KEY (id)
);

ALTER TABLE articles
    ADD CONSTRAINT FK_ARTICLES_ON_ID_CATEGORIES FOREIGN KEY (id_categories) REFERENCES categories (id);

ALTER TABLE articles
    ADD CONSTRAINT FK_ARTICLES_ON_ID_ENTERPRISE FOREIGN KEY (id_enterprise) REFERENCES entreprises (id);

ALTER TABLE clients
    ADD CONSTRAINT FK_CLIENTS_ON_ID_ENTERPRISE FOREIGN KEY (id_enterprise) REFERENCES entreprises (id);

ALTER TABLE commande_clients
    ADD CONSTRAINT FK_COMMANDECLIENTS_ON_ID_CLIENT FOREIGN KEY (id_client) REFERENCES clients (id);

ALTER TABLE commande_fournisseurs
    ADD CONSTRAINT FK_COMMANDEFOURNISSEURS_ON_ID_FOURNISSEUR FOREIGN KEY (id_fournisseur) REFERENCES fournisseurs (id);

ALTER TABLE fournisseurs
    ADD CONSTRAINT FK_FOURNISSEURS_ON_ID_ENTERPRISE FOREIGN KEY (id_enterprise) REFERENCES entreprises (id);

ALTER TABLE ligne_commande_clients
    ADD CONSTRAINT FK_LIGNECOMMANDECLIENTS_ON_ID_ARTICLE FOREIGN KEY (id_article) REFERENCES articles (id);

ALTER TABLE ligne_commande_clients
    ADD CONSTRAINT FK_LIGNECOMMANDECLIENTS_ON_ID_COMMANDE_CLIENT FOREIGN KEY (id_commande_client) REFERENCES commande_clients (id);

ALTER TABLE ligne_commande_fournisseurs
    ADD CONSTRAINT FK_LIGNECOMMANDEFOURNISSEURS_ON_ID_ARTICLE FOREIGN KEY (id_article) REFERENCES articles (id);

ALTER TABLE ligne_commande_fournisseurs
    ADD CONSTRAINT FK_LIGNECOMMANDEFOURNISSEURS_ON_ID_COMMANDE_FOURNISSEUR FOREIGN KEY (id_commande_fournisseur) REFERENCES commande_fournisseurs (id);

ALTER TABLE ligne_ventes
    ADD CONSTRAINT FK_LIGNEVENTES_ON_ID_ARTICLES FOREIGN KEY (id_articles) REFERENCES articles (id);

ALTER TABLE ligne_ventes
    ADD CONSTRAINT FK_LIGNEVENTES_ON_ID_VENTE FOREIGN KEY (id_vente) REFERENCES ventes (id);

ALTER TABLE mouvement_stock
    ADD CONSTRAINT FK_MOUVEMENTSTOCK_ON_ID_ARTICLE FOREIGN KEY (id_article) REFERENCES articles (id);

ALTER TABLE ventes
    ADD CONSTRAINT FK_VENTES_ON_ID_ENTERPRISE FOREIGN KEY (id_enterprise) REFERENCES entreprises (id);